config {
  type: "view", // Creates a view in BigQuery. Try changing to "table" instead.
  columns: {
    zipcode: "The zip code",
    gender: "male or female",
  }
}

SELECT
  zipcode,
  population,
  gender,
  2010 AS census_year
FROM
  `bigquery-public-data.census_bureau_usa.population_by_zip_2010` UNION
SELECT
  zipcode,
  population,
  gender,
  2000 AS census_year
FROM
  `bigquery-public-data.census_bureau_usa.population_by_zip_2000`
